### ISSUE TITLE
Registers an unload listener

### ISSUE THREAD

**Issue by g-u-r-k-a-n** [yandex/metrica-tag#9]
I have been using the metrica for years but this warning has been there for a long time and is reducing my ranking and score. So, this case is the same for all sites using metrica. To be honest, I don't think you will care much about Google, but can't you find another solution for this `unload` event?

The warning is :
>The unload event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use pagehide or visibilitychange events instead. [Learn more about unload event listeners](https://web.dev/bfcache/?utm_source=lighthouse&utm_medium=devtools#never-use-the-unload-event)

## With Yandex Metrica
![image](https://github.com/yandex/metrica-tag/assets/55924924/219cf231-f023-4a7d-bb06-6c47e263edc3)

## Without Yandex Metrica
![image](https://github.com/yandex/metrica-tag/assets/55924924/f83bd655-a421-4858-89fa-739bb9887134)

**Comment by sedx** [comment]
Faced same issue.
When enable `webvisor: true` during initialisation `unload` events attach to window.
When webvisor is disabled bf cache works perfectly!

**Comment by g-u-r-k-a-n** [comment]
@sedx Thank you for your help and also for doing what Yandex should do.👍 This way it doesn't really throw any errors but I have no idea what this `webvisor` property is. Based on what I've looked into, I suspect this is the one that provides all the useful events and if I disable it there would be no point in using metrica. So do you know which features are disabled this way?

**Comment by sedx** [comment]
@g-u-r-k-a-n  It's kind of user session recording tool. You can read more here https://yandex.ru/support/metrica/webvisor/about-webvisor.html?lang=en

**Comment by g-u-r-k-a-n** [comment]
Yes, I took a look at smilar links before writing the post above, but it is not clear what exactly is in any of the documents, thanks. Then I disabled webvisor and that day "Session Replay" and some other tools did not work, which is exactly why I use metrica😄

As is seen from this thread, Yandex is not even interested in the issue, let alone fixing it.
![image](https://github.com/yandex/metrica-tag/assets/55924924/b5ed2a55-2d72-46d8-a179-d487e5b68968)

After all, I'll review it for a few more days, and I will say goodbye to metrica if it still reduces the ranking.

**Comment by enovikov11** [comment]
Hello!

The **unload** event is used to reliably send data to Yandex Metrica and accurately record a Webvisor session. Currently, our team is working on an alternative to the **unload** event to support changes proposed by [Google](https://developer.chrome.com/articles/deprecating-unload/).

If you still have questions — contact [customer support](https://yandex.ru/support/metrica/troubleshooting.html?lang=en) and we will help you sort out your situation.

**Comment by EvgeniSasim** [comment]
How's it going? @enovikov11

**Comment by enovikov11** [comment]
We found technical limitation that stops us from implementing bfcache support
<img width="700" alt="image" src="https://github.com/yandex/metrica-tag/assets/54208584/b6020a86-7f9a-4586-925e-0833f2d870e6">

Some time passed since then, so its good idea to re-check that.

P.S. For Yandex employees: you can track task [here](https://nda.ya.ru/t/d4mWL96n74NBAv)

**Comment by sabio-yateam** [comment]
Webvisor is not a part of this repository, thus there is no need to track its progress here. For any details, refer to [the previous comment](https://github.com/yandex/metrica-tag/issues/9#issuecomment-1828048837).

PS. We do have  an `unload` [handler](https://github.com/yandex/metrica-tag/blob/main/src/utils/time/time.ts#L40), though it's a fallback for ancient browsers and won't affect any modern audits.

**Comment by g-u-r-k-a-n** [comment]
@sabio-yateam
>won't affect any modern audits.

Wait, what do you mean? It seems that you all are work pretty joclosely and funny.

## I took the screenshot above 3 months ago, not 10 years ago.

The issue's as clear as day and the solution is to use different events than unload or beforeunload.

@g-u-r-k-a-n 
>I don't think you will care much about Google
>![image](https://github.com/yandex/metrica-tag/assets/55924924/b5ed2a55-2d72-46d8-a179-d487e5b68968)

Anyway,  thank you all for not misleading me though.
